version: '3.8'

services:
  fastapi-app:
    image: gcr.io/ozu-tokenise/fastapi-app:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PLATFORM=linux/amd64
    ports:
      - "8080:8080"
